_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
alg_cfg:
    value:
        clip_param: 0.2
        desired_kl: 0.01
        entropy_coef: 0.01
        gamma: 0.99
        lam: 0.95
        learning_rate: 0.001
        max_grad_norm: 1
        num_learning_epochs: 5
        num_mini_batches: 4
        schedule: adaptive
        use_clipped_value_loss: true
        value_loss_coef: 1
log_dir:
    value: /home/jay/genesis_wlr/logs/flamingo_v1_5_1/stand_Apr20_02-33-54
policy_cfg:
    value:
        activation: elu
        actor_hidden_dims:
            - 512
            - 256
            - 128
        critic_hidden_dims:
            - 512
            - 256
            - 128
        init_noise_std: 1
runner_cfg:
    value:
        algorithm:
            clip_param: 0.2
            desired_kl: 0.01
            entropy_coef: 0.01
            gamma: 0.99
            lam: 0.95
            learning_rate: 0.001
            max_grad_norm: 1
            num_learning_epochs: 5
            num_mini_batches: 4
            schedule: adaptive
            use_clipped_value_loss: true
            value_loss_coef: 1
        checkpoint: -1
        empirical_normalization: false
        experiment_name: flamingo_v1_5_1
        load_run: -1
        logger: wandb
        max_iterations: 3000
        num_steps_per_env: 24
        policy:
            activation: elu
            actor_hidden_dims:
                - 512
                - 256
                - 128
            critic_hidden_dims:
                - 512
                - 256
                - 128
            init_noise_std: 1
        resume: false
        resume_path: null
        run_name: stand
        runner_class_name: OnPolicyRunner
        save_interval: 100
        seed: 42
        wandb_project: flamingo_v1_5_1
